export const dailyTasks = [
  {
    id: 1,
    title: '30-minute workout session',
    category: 'Fitness',
    xp: 80,
    completed: false,
  },
  {
    id: 2,
    title: 'Morning stretch and mobility routine',
    category: 'Fitness',
    xp: 40,
    completed: false,
  },
  {
    id: 3,
    title: 'Practice 2 coding challenges on LeetCode',
    category: 'Coding',
    xp: 100,
    completed: false,
  },
  {
    id: 4,
    title: 'Review and summarize one programming concept',
    category: 'Coding',
    xp: 60,
    completed: false,
  },
  {
    id: 5,
    title: 'Study 45 minutes for upcoming exam',
    category: 'Study',
    xp: 90,
    completed: false,
  },
  {
    id: 6,
    title: 'Complete one chapter review quiz',
    category: 'Study',
    xp: 70,
    completed: false,
  },
  {
    id: 7,
    title: 'Practice 20 minutes of English speaking',
    category: 'English',
    xp: 65,
    completed: false,
  },
  {
    id: 8,
    title: 'Write and review 10 new vocabulary words',
    category: 'English',
    xp: 50,
    completed: false,
  },
  {
    id: 9,
    title: 'Track spending and update weekly budget',
    category: 'Money',
    xp: 55,
    completed: false,
  },
  {
    id: 10,
    title: 'Set aside 10 minutes to review savings goal',
    category: 'Money',
    xp: 45,
    completed: false,
  },
];
